INFO 2021-04-10 05:23:54,622  Watching for file changes with StatReloader
WARNING 2021-04-10 05:24:13,773  Bad Request: /api/signup
WARNING 2021-04-10 05:24:13,773  "POST /api/signup HTTP/1.1" 400 84
INFO 2021-04-10 05:24:22,449  user ram@gmail.com registered successfully
INFO 2021-04-10 05:24:22,449  "POST /api/signup HTTP/1.1" 201 78
INFO 2021-04-10 05:26:16,447  C:\Users\Asus\PycharmProjects\TodoAppApi\todorest\userprofile\views.py changed, reloading.
INFO 2021-04-10 05:26:16,913  Watching for file changes with StatReloader
INFO 2021-04-10 05:26:25,268  user ram@gmail.comlogged in  successfully
INFO 2021-04-10 05:26:25,269  "POST /api/signin HTTP/1.1" 200 327
WARNING 2021-04-10 05:26:40,763  Method Not Allowed: /api/profile
WARNING 2021-04-10 05:26:40,764  "POST /api/profile HTTP/1.1" 405 41
INFO 2021-04-10 05:26:45,486  "GET /api/profile HTTP/1.1" 200 183
INFO 2021-04-10 05:27:08,334  "POST /api/profile/update HTTP/1.1" 200 2
INFO 2021-04-10 05:27:16,823  "GET /api/profile HTTP/1.1" 200 183
INFO 2021-04-10 05:27:27,282  "GET /api/profile HTTP/1.1" 200 183
ERROR 2021-04-10 05:27:51,065  Internal Server Error: /api/profile/update
Traceback (most recent call last):
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\todorest\userprofile\views.py", line 61, in post
    logger.info('user ' + profile.email + ' updated account')
AttributeError: 'UserProfile' object has no attribute 'email'
ERROR 2021-04-10 05:27:51,066  "POST /api/profile/update HTTP/1.1" 500 96193
ERROR 2021-04-10 05:28:06,657  Internal Server Error: /api/profile/update
Traceback (most recent call last):
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Asus\PycharmProjects\TodoAppApi\todorest\userprofile\views.py", line 61, in post
    logger.info('user ' + profile.email + ' updated account')
AttributeError: 'UserProfile' object has no attribute 'email'
ERROR 2021-04-10 05:28:06,658  "POST /api/profile/update HTTP/1.1" 500 96193
INFO 2021-04-10 05:28:26,664  C:\Users\Asus\PycharmProjects\TodoAppApi\todorest\userprofile\views.py changed, reloading.
INFO 2021-04-10 05:28:27,126  Watching for file changes with StatReloader
INFO 2021-04-10 05:28:35,761  C:\Users\Asus\PycharmProjects\TodoAppApi\todorest\userprofile\views.py changed, reloading.
INFO 2021-04-10 05:28:36,204  Watching for file changes with StatReloader
INFO 2021-04-10 05:28:43,913  C:\Users\Asus\PycharmProjects\TodoAppApi\todorest\userprofile\views.py changed, reloading.
INFO 2021-04-10 05:28:44,338  Watching for file changes with StatReloader
INFO 2021-04-10 05:28:49,121  user ram updated account
INFO 2021-04-10 05:28:49,122  "POST /api/profile/update HTTP/1.1" 200 137
